<a href="https://colab.research.google.com/github/acwing-xlh/pytorch/blob/main/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import torch
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# tensor的创建


In [12]:
# 直接通过数据进行创建
x = torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [13]:
# 通过ndarray进行创建
x = np.array([1,2,3])
x = torch.from_numpy(x)
x

tensor([1, 2, 3])

In [14]:
# 通过其他tensor进行创建
x_ones = torch.ones_like(x)
x_ones

tensor([1, 1, 1])

In [15]:
x_zeros = torch.zeros_like(x)
x_zeros

tensor([0, 0, 0])

In [16]:
# 按照形状进行初始化
x_rand = torch.rand((5,3))
x_rand

tensor([[0.7243, 0.8988, 0.8813],
        [0.7516, 0.0754, 0.5707],
        [0.2583, 0.6368, 0.7984],
        [0.7121, 0.8944, 0.7319],
        [0.3643, 0.7593, 0.0931]])

In [17]:
x_ones = torch.ones((5,3))
x_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

# tensor的属性

In [18]:
x = torch.tensor([[1,2,3],[1,2,3]])
# tensor的形状
x.shape

torch.Size([2, 3])

In [19]:
# tensor的数据类型
x.dtype

torch.int64

In [20]:
# tensor的设备
x.device

device(type='cpu')

In [21]:
if torch.cuda.is_available:
  x = x.to("cuda")

In [22]:
x.device

device(type='cuda', index=0)

#  tensor的运算


In [24]:
# tensor的切片操作
tensor = torch.rand((5,3))
tensor

tensor([[0.2204, 0.2151, 0.2278],
        [0.3908, 0.0660, 0.2739],
        [0.1014, 0.8561, 0.3283],
        [0.5501, 0.5038, 0.7631],
        [0.0406, 0.5363, 1.0000]])

In [25]:
tensor[:,0]

tensor([0.2204, 0.3908, 0.1014, 0.5501, 0.0406])

In [26]:
tensor[0:2,1]

tensor([0.2151, 0.0660])

In [28]:
# tensor的拼接操作
x = torch.ones((1,2))
y = torch.zeros((1,2))

In [39]:
result = torch.cat([x,y],dim=0)
result.shape

torch.Size([2, 2])

In [61]:
# tensor的算数运算
x = torch.ones((3,2))
y = torch.ones((2,3))

In [46]:
## tensor的转置
xT = x.T
xT

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [47]:
## tensor的矩阵乘法
result = x.matmul(y)
result

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [58]:
## 单一元素tensor转python数字
agg = x.sum()
agg_item = agg.item()
type(agg_item)

float

In [62]:
## in_place操作--直接修改自己
x.add_(torch.ones_like(x))
x

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

# tensor和numpy的转换


In [63]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
data_tensor = torch.from_numpy(data)
data_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [65]:
data_numpy = data_tensor.numpy()
data_numpy

array([[1, 2, 3],
       [4, 5, 6]])

# 修改tensor的形状

In [66]:
x = torch.rand((4,4))
x.shape

torch.Size([4, 4])

In [67]:
x = x.view(-1,2)
x.shape

torch.Size([8, 2])

# tensor的自动求导
* tensor的requires_grad属性表示是否追踪对该tensor的操作.当完成计算后能够使用backward()来进行反向传播，梯度会被**累加**到grad属性上
* 可以使用with torch.no_grad()将不想被追踪的操作代码块包裹起来
* tensor.requires_grad_() 修改该属性为true
* 梯度会进行累加，因此当不需要前面累加的梯度时，需要使用tensor.grad.data.zeros_()清空





In [70]:
x = torch.ones(2,2,requires_grad=True)
print(x)
print(x.grad_fn)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
None


In [72]:
y = x+2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [74]:
z = y * y * 3
out = z.mean()
print(z)
print(out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)
tensor(27., grad_fn=<MeanBackward0>)


In [91]:
# 使用in-place方式改变requeires_grad属性
a = torch.randn(2,2)
a.requires_grad

False

In [93]:
a.requires_grad_()
a.requires_grad

True

In [94]:
# 梯度
out.backward()

In [95]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [98]:
out2 = x.sum()
out2.backward()
print(x.grad)

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])


In [100]:
out3 = x.sum()
x.grad.data.zero_()  # 梯度会累加，因此每次都需要清零
out3.backward()
print(x.grad)

tensor([[1., 1.],
        [1., 1.]])
